### ISSUE TITLE
Infografía de Hilos

### ISSUE THREAD

**Issue by Nayee123** [SistemasTecTlaxiaco/infografia-de-hilos-Nayee123#2]
[Hilos en c#.pdf](https://github.com/SistemasTecTlaxiaco/infografia-de-hilos-Nayee123/files/6461257/Hilos.en.c.pdf)

**Comment by Rosa218** [comment]
Calificación: 20/20

**Comment by josealfredo79** [comment]
Bien hecho y revisado
